apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snowflake-app-chat.fullname" . }}
  labels:
    {{- include "snowflake-app-chat.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "snowflake-app-chat.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategy.type }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "snowflake-app-chat.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "snowflake-app-chat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- if .Values.sideCar.enabled }}
      - name: {{ .Chart.Name }}-sidecar
        image: {{ .Values.sideCar.image.repository }}:{{ .Values.sideCar.image.tag }}
        imagePullPolicy: {{ .Values.sideCar.imagePullPolicy | default "Always" }}
        {{- if .Values.sideCar.resources.enabled }}
        resources:
          requests:
            cpu: {{ .Values.sideCar.resources.requests.cpu }}
            memory: {{ .Values.sideCar.resources.requests.memory }}
        {{- end }}
        lifecycle:
          preStop:
            exec: 
              command: ["/bin/sh", "-c", "sleep 30"]
        args:
        - "-config.file=/etc/promtail/promtail.yaml"
        - "-config.expand-env=true"
        {{- with .Values.env }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.sideCar.volumeMounts }}
        volumeMounts:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}  
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy | default "Always" }}
        {{- with .Values.ports }}
        ports:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.livenessProbe.httpGet.port }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: {{ .Values.startupProbe.httpGet.path }}
            port: {{ .Values.startupProbe.httpGet.port }}
            scheme: HTTP
            httpHeaders:
              - name: X-Forwarded-Proto
                value: http
          failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds}}
        {{- end }}
        resources: 
        {{- toYaml .Values.resources | nindent 10 }}
        {{- with .Values.mainContainer.volumeMounts }}
        # command: []
        # args: []      
        volumeMounts:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
