{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "snowflake-app-chat.fullname" . }}
  labels:
    {{- include "snowflake-app-chat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "snowflake-app-chat.selectorLabels" . | nindent 4 }}
{{- end }}
